name: Lint

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake
      - name: Run isort
        run: isort --check --diff .
      - name: Run black
        run: black --check --diff .
      - name: Run autoflake
        run: autoflake --check --diff --recursive .
